import "./globals.css";
import Navbar from "../components/home/Navbar.jsx"
import Footer from "../components/home/Footer.jsx"
import { Labrada } from 'next/font/google'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const labrada = Labrada({
  subsets: ["latin"],
  variable: "--font-labrada",
  weight: ["300", "400", "500", "600", "700"],
});


export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={labrada.variable}>
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
